### ISSUE TITLE
[nl] rue Étoile est 1 mot en néerlandais / Star street is one word in Dutch

### ISSUE THREAD

**Issue by ghost** [Deevad/peppercarrot_ep16_translation#7]
"Rue Étoile" devient "Sterstraat", ce qui est trop long pour aller sur la plaque de rue. On peut le césurer, mais ce n'est pas élégant et il serait pratique de savoir si vous n'avez pas pensé de changer les dimensions de toute façon, @Deevad, _avant_ qu'on fasse cela. :smiley: Peut-être il serait mieux d'attendre la version finale du dessin ?

"Sterstraat" is too long to fit. We could hyphenate it, @Willem3141, but I'm asking David whether he plans to change the sign dimensions anyway _before_ we do that. :smiley:

**Comment by Deevad** [comment]
![2016-04-29_screenshot_001](https://cloud.githubusercontent.com/assets/4021867/14903068/eb4ac5ac-0d9e-11e6-8e56-0984f4d5834d.png)

mm... I see. It's a bit too risky to change the size of the artwork now, ( or we'll have to offset every other language to center a new hypothetic boundaries ). Sorry for the small size. 
At 40% viewport size ( zoom) in Inkscape it's similar to the webcomic page zoom. Maybe the size of the font can be reduced ? Maybe all capital but reduced font-size ? Just ideas :)

**Comment by Willem3141** [comment]
@Deevad Will the Rue Étoile be mentioned in a future episode? If not, we can maybe take a bit more freedom and make it a direction sign pointing to the market like

> Markt
> →

which would fit nicely in the sign. But of course it changes the meaning drastically. Do you like a solution like that?

**Comment by Deevad** [comment]
@Willem3141  +1 for freedom  :)

No, 'Star Street' will not be mentioned again. It's really an 'accessory' label in the street ; just to create the mood of a city. A sign to go to the market is perfect too.
